#pragma once

#include <wrl.h>
#include <wrl/client.h>
#include <d3d11_2.h>
#include <d2d1_2.h>
#include <d2d1effects_1.h>
#include <dwrite_2.h>
#include <wincodec.h>
#include <DirectXColors.h>
#include <DirectXMath.h>
#include <memory>
#include <agile.h>
#include <concrt.h>
#include <string>
#include "boost/algorithm/string.hpp"
#include "boost/lexical_cast.hpp"
#include <vector>
#include <fstream>
#include "Helpers.h"